// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//	plus functions to determine game mode (shareware, registered),
//	parse command line parameters, configure game parameters (turbo),
//	and call the startup functions.
//
//-----------------------------------------------------------------------------


static const char rcsid[] = "$Id: d_main.c,v 1.8 1997/02/03 22:45:09 b1 Exp $";

#define	BGCOLOR		7
#define	FGCOLOR		8


#if defined(NORMALUNIX) || defined(N64)
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#ifndef O_BINARY
#define O_BINARY 0
#endif
#endif


#include "doomdef.h"
#include "doomstat.h"

#include "dstrings.h"
#include "sounds.h"
#include "d_items.h"


#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_argv.h"
#include "m_misc.h"
#include "m_menu.h"

#include "i_system.h"
#include "i_sound.h"
#include "i_video.h"

#include "g_game.h"

#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"

#include "p_setup.h"
#include "r_local.h"


#include "d_main.h"
#ifdef N64
#include "i_wad_browser_n64.h"
#include "i_main_n64.h"
#include "n64_debug.h"
#endif

//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
void D_DoomLoop (void);


char*		wadfiles[MAXWADFILES];


boolean		devparm;	// started game with -devparm
boolean         nomonsters;	// checkparm of -nomonsters
boolean         respawnparm;	// checkparm of -respawn
boolean         fastparm;	// checkparm of -fast

boolean         drone;

boolean		singletics = false; // debug flag to cancel adaptiveness



//extern int soundVolume;
//extern  int	sfxVolume;
//extern  int	musicVolume;

extern  boolean	inhelpscreens;

skill_t		startskill;
int             startepisode;
int		startmap;
boolean		autostart;

FILE*		debugfile;

boolean		advancedemo;




char		wadfile[1024];		// primary wad file
char		mapdir[1024];           // directory of development maps
char		basedefault[1024];      // default file


void D_CheckNetGame (void);
void D_ProcessEvents (void);
void G_BuildTiccmd (ticcmd_t* cmd);
void D_DoAdvanceDemo (void);
#ifdef N64
void G_BuildTiccmdN64Local(ticcmd_t* cmd, int playernum, const n64_local_input_t* input);
#endif


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t         events[MAXEVENTS];
int             eventhead;
int 		eventtail;


//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead] = *ev;
	eventhead = (eventhead + 1) & (MAXEVENTS-1);
}


//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t*	ev;
	
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ( ( gamemode == commercial )
	 && (W_CheckNumForName("map01")<0) )
      return;
	
    for ( ; eventtail != eventhead ; eventtail = (eventtail + 1) & (MAXEVENTS-1) )
    {
	ev = &events[eventtail];
	if (M_Responder (ev))
	    continue;               // menu ate the event
	G_Responder (ev);
    }
}




//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t     wipegamestate = GS_DEMOSCREEN;
extern  boolean setsizeneeded;
extern  int             showMessages;
extern  int             detailLevel;
extern  int             screenblocks;
extern  int             setblocks;
extern  int             setdetail;
void R_ExecuteSetViewSize (void);
int M_StringWidth(char* string);

#ifdef N64
typedef struct d_n64_split_rect_s
{
	int x;
	int y;
	int w;
	int h;
} d_n64_split_rect_t;

#define N64_SPLIT_HUD_PAD_X 2
#define N64_SPLIT_HUD_TEXT_Y_OFFSET 10
#define N64_SPLIT_HUD_KEY_ROW_H 9
#if DEBUG
#define N64_SPLIT_FPS_PAD_X 2
#define N64_SPLIT_FPS_PAD_Y 2

static int d_n64_debug_fps = 0;
static int d_n64_debug_fps_frames = 0;
static int d_n64_debug_fps_lasttic = -1;
static char d_n64_debug_fps_text[16] = "0";

static void D_N64UpdateDebugFps(void)
{
	int nowtic;
	int elapsed;

	nowtic = I_GetTime();

	if (d_n64_debug_fps_lasttic < 0)
	{
		d_n64_debug_fps_lasttic = nowtic;
		d_n64_debug_fps_frames = 0;
		d_n64_debug_fps = 0;
		sprintf(d_n64_debug_fps_text, "%d", d_n64_debug_fps);
		return;
	}

	d_n64_debug_fps_frames++;
	elapsed = nowtic - d_n64_debug_fps_lasttic;

	if (elapsed >= TICRATE)
	{
		d_n64_debug_fps = (d_n64_debug_fps_frames * TICRATE + (elapsed / 2)) / elapsed;
		d_n64_debug_fps_frames = 0;
		d_n64_debug_fps_lasttic = nowtic;
		sprintf(d_n64_debug_fps_text, "%d", d_n64_debug_fps);
	}
}

static void D_N64DrawDebugFps(const d_n64_split_rect_t* pane_rect)
{
	int text_x;
	int text_width;

	if (!pane_rect)
	    return;

	if (pane_rect->w < 1 || pane_rect->h < 1)
	    return;

	text_width = M_StringWidth(d_n64_debug_fps_text);
	text_x = pane_rect->x + pane_rect->w - N64_SPLIT_FPS_PAD_X - text_width;
	if (text_x < pane_rect->x + N64_SPLIT_FPS_PAD_X)
	    text_x = pane_rect->x + N64_SPLIT_FPS_PAD_X;

	M_DrawText(text_x,
		   pane_rect->y + N64_SPLIT_FPS_PAD_Y,
		   true,
		   d_n64_debug_fps_text);
}
#endif

static int D_N64GetPlayerHudAmmo(const player_t* player)
{
	ammotype_t ammotype;

	if (!player)
	    return -1;

	ammotype = weaponinfo[player->readyweapon].ammo;
	if (ammotype == am_noammo)
	    return -1;

	return player->ammo[ammotype];
}

static void D_N64DrawSplitHud(const d_n64_split_rect_t* pane_rect, int playernum)
{
	player_t* player;
	int text_y;
	int health;
	int armor;
	int ammo;
	char hudline[48];

	if (!pane_rect)
	    return;

	if (playernum < 0 || playernum >= MAXPLAYERS || !playeringame[playernum])
	    return;

	if (pane_rect->w < 1 || pane_rect->h < 1)
	    return;

	player = &players[playernum];
	text_y = pane_rect->y + pane_rect->h - N64_SPLIT_HUD_TEXT_Y_OFFSET;
	if (text_y < pane_rect->y)
	    text_y = pane_rect->y;

	health = player->health;
	if (health < 0)
	    health = 0;

	armor = player->armorpoints;
	if (armor < 0)
	    armor = 0;

	ammo = D_N64GetPlayerHudAmmo(player);
	if (ammo >= 0)
	    sprintf(hudline, "P%d H%d A%d M%d", playernum + 1, health, armor, ammo);
	else
	    sprintf(hudline, "P%d H%d A%d M-", playernum + 1, health, armor);

	M_DrawText(pane_rect->x + N64_SPLIT_HUD_PAD_X,
		   text_y,
		   true,
		   hudline);

	// Draw keycard/skull icons on the row above the stats line so each
	// split-screen player can see who holds which keys.
	{
	    int key_y;
	    int key_max_x;

	    key_y = text_y - N64_SPLIT_HUD_KEY_ROW_H;
	    if (key_y < pane_rect->y)
		key_y = pane_rect->y;

	    key_max_x = pane_rect->x + pane_rect->w - N64_SPLIT_HUD_PAD_X;

	    ST_DrawSplitKeys(pane_rect->x + N64_SPLIT_HUD_PAD_X,
			     key_y,
			     key_max_x,
			     playernum);
	}
}

static int D_N64CountActivePlayers(void)
{
	int i;
	int count;

	if (gamestate != GS_LEVEL || !D_LocalMultiplayerEnabled() || !netgame)
		return 1;

	count = 0;
	for (i = 0; i < MAXPLAYERS; i++)
		if (playeringame[i] && players[i].mo)
		    count++;

	if (count < 1)
		count = 1;

	return count;

}

static void D_N64GetSplitRect(int splitplayers, int view_index, d_n64_split_rect_t* rect)
{
	if (!rect)
	    return;

	rect->x = 0;
	rect->y = 0;
	rect->w = 0;
	rect->h = 0;

	if (view_index < 0)
	    return;

	if (splitplayers <= 2)
	{
	    if (view_index == 0)
	    {
		rect->x = 0;
		rect->y = 0;
		rect->w = SCREENWIDTH;
		rect->h = SCREENHEIGHT / 2;
	    }
	    else if (view_index == 1)
	    {
		rect->x = 0;
		rect->y = SCREENHEIGHT / 2;
		rect->w = SCREENWIDTH;
		rect->h = SCREENHEIGHT / 2;
	    }
	    return;
	}

	if (splitplayers == 3)
	{
	    switch (view_index)
	    {
	      case 0:
		rect->x = 0;
		rect->y = 0;
		rect->w = SCREENWIDTH / 2;
		rect->h = SCREENHEIGHT / 2;
		break;
	      case 1:
		rect->x = SCREENWIDTH / 2;
		rect->y = 0;
		rect->w = SCREENWIDTH / 2;
		rect->h = SCREENHEIGHT / 2;
		break;
	      case 2:
		rect->x = 0;
		rect->y = SCREENHEIGHT / 2;
		rect->w = SCREENWIDTH / 2;
		rect->h = SCREENHEIGHT / 2;
		break;
	      default:
		break;
	    }
	    return;
	}

	switch (view_index)
	{
	  case 0:
	    rect->x = 0;
	    rect->y = 0;
	    rect->w = SCREENWIDTH / 2;
	    rect->h = SCREENHEIGHT / 2;
	    break;
	  case 1:
	    rect->x = SCREENWIDTH / 2;
	    rect->y = 0;
	    rect->w = SCREENWIDTH / 2;
	    rect->h = SCREENHEIGHT / 2;
	    break;
	  case 2:
	    rect->x = 0;
	    rect->y = SCREENHEIGHT / 2;
	    rect->w = SCREENWIDTH / 2;
	    rect->h = SCREENHEIGHT / 2;
	    break;
	  case 3:
	    rect->x = SCREENWIDTH / 2;
	    rect->y = SCREENHEIGHT / 2;
	    rect->w = SCREENWIDTH / 2;
	    rect->h = SCREENHEIGHT / 2;
	    break;
	  default:
	    break;
	}
}

// Correctness-first split detail policy: forcing blocky low detail in 3-4P can
// reveal tiny multiplayer sprite fragments at wall edges due coarse occlusion
// quantization. Keep user's configured detail for all split layouts.
static int D_N64SplitDetail(int splitplayers)
{
	(void)splitplayers;
	return detailLevel;
}

static void D_N64EnsureSplitViewSize(int width, int height, int detail)
{
	if (width < 1 || height < 1)
	    return;

	if (scaledviewwidth != width || viewheight != height || detailshift != detail)
	{
	    R_SetN64ViewSize(width, height, detail);
	    R_ExecuteSetViewSize();
	}
}

static void D_N64PrepareSplitViewSize(int splitplayers)
{
	int normalwidth;
	int normalheight;
	int splitwidth;
	int splitheight;

	if (splitplayers > 1)
	{
	    splitwidth = (splitplayers <= 2) ? SCREENWIDTH : (SCREENWIDTH / 2);
	    splitheight = SCREENHEIGHT / 2;

	    D_N64EnsureSplitViewSize(splitwidth, splitheight, D_N64SplitDetail(splitplayers));
	    return;
	}

	R_ClearN64ViewSizeOverride();

	if (screenblocks == 11)
	{
	    normalwidth = SCREENWIDTH;
	    normalheight = SCREENHEIGHT;
	}
	else
	{
	    normalwidth = screenblocks * 32;
	    normalheight = (screenblocks * 168 / 10) & ~7;
	}

	if (setblocks != screenblocks
	    || setdetail != detailLevel
	    || scaledviewwidth != normalwidth
	    || viewheight != normalheight)
	{
	    R_SetViewSize(screenblocks, detailLevel);
	    R_ExecuteSetViewSize();
	}
}
#endif

void D_Display (void)
{
    static  boolean		viewactivestate = false;
    static  boolean		menuactivestate = false;
    static  boolean		inhelpscreensstate = false;
    static  boolean		fullscreen = false;
    static  gamestate_t		oldgamestate = -1;
    static  int			borderdrawcount;
    int				nowtime;
    int				tics;
    int				wipestart;
    int				y;
	int                         splitplayers;
#ifdef N64
	int                         i;
	int                         splitslot;
	int                         restoredisplayplayer;
	int                         splitdetail;
	d_n64_split_rect_t          splitrect;
	d_n64_split_rect_t          viewrect;
#endif
    boolean			done;
    boolean			wipe;
    boolean			redrawsbar;

    if (nodrawers)
	return;                    // for comparative timing / profiling

#ifdef N64
	splitplayers = D_N64CountActivePlayers();
	D_N64PrepareSplitViewSize(splitplayers);
#else
	splitplayers = 1;
#endif
		
    redrawsbar = false;
    
    // change the view size if needed
    if (setsizeneeded)
    {
	R_ExecuteSetViewSize ();
	oldgamestate = -1;                      // force background redraw
	borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
	wipe = true;
	wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
	wipe = false;

    if (gamestate == GS_LEVEL && gametic)
	HU_Erase();
    
    // do buffered drawing
    switch (gamestate)
    {
      case GS_LEVEL:
	if (!gametic)
	    break;
	if (automapactive)
	    AM_Drawer ();
	if (wipe || (viewheight != 200 && fullscreen) )
	    redrawsbar = true;
	if (inhelpscreensstate && !inhelpscreens)
	    redrawsbar = true;              // just put away the help screen
	if (splitplayers < 2)
	{
	    ST_Drawer (viewheight == 200, redrawsbar );
	    fullscreen = viewheight == 200;
	}
	else
	{
	    fullscreen = true;
	}
	break;

      case GS_INTERMISSION:
	WI_Drawer ();
	break;

      case GS_FINALE:
	F_Drawer ();
	break;

      case GS_DEMOSCREEN:
	D_PageDrawer ();
	break;
    }
    
    // draw buffered stuff to screen
    I_UpdateNoBlit ();
    
    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic)
	{
#ifdef N64
#if DEBUG
	    D_N64UpdateDebugFps();
#endif
	    if (splitplayers > 1)
	    {
		restoredisplayplayer = displayplayer;
		splitslot = 0;
		splitdetail = D_N64SplitDetail(splitplayers);
		I_N64SplitScreenBeginFrame(splitplayers);
		for (i = 0; i < MAXPLAYERS; i++)
		{
		    if (!playeringame[i] || !players[i].mo)
			continue;

		    D_N64GetSplitRect(splitplayers, splitslot, &splitrect);
		    viewrect = splitrect;

		    if (viewrect.w <= 0 || viewrect.h <= 0)
		    {
			splitslot++;
			continue;
		    }

		    // NOTE: 4-player interleaving (rendering only half the quadrants
		    // per frame) was attempted here for perf, but produced "ghost
		    // player through walls" artifacts: stale quadrants kept the
		    // previous tic's sprite positions while game logic continued
		    // advancing, so other players appeared at old locations that the
		    // current world geometry now occludes. Always render every active
		    // player's view to keep visuals correct.

		    D_N64EnsureSplitViewSize(viewrect.w, viewrect.h, splitdetail);
		    R_SetViewWindow(viewrect.x, viewrect.y);

		    displayplayer = i;
		    R_RenderPlayerView (&players[i]);
		    D_N64DrawSplitHud(&splitrect, i);
		    splitslot++;
		}
		if (splitslot > 0)
		    I_N64SplitScreenEndFrame();
		else
		    R_RenderPlayerView (&players[restoredisplayplayer]);
	    #if DEBUG
		splitrect.x = 0;
		splitrect.y = 0;
		splitrect.w = SCREENWIDTH;
		splitrect.h = SCREENHEIGHT;
		D_N64DrawDebugFps(&splitrect);
	    #endif
		displayplayer = restoredisplayplayer;
	    }
	    else
#endif
	    {
		R_RenderPlayerView (&players[displayplayer]);
	#ifdef N64
	#if DEBUG
		viewrect.x = viewwindowx;
		viewrect.y = viewwindowy;
		viewrect.w = scaledviewwidth;
		viewrect.h = viewheight;
		D_N64DrawDebugFps(&viewrect);
	#endif
	#endif
	    }
	}


    if (gamestate == GS_LEVEL && gametic && splitplayers < 2)
	HU_Drawer ();
    
    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
	I_SetPalette (W_CacheLumpName ("PLAYPAL",PU_CACHE));

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
	viewactivestate = false;        // view was not active
	if (splitplayers < 2)
	    R_FillBackScreen ();    // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL
	&& !automapactive
	&& scaledviewwidth != 320
	&& splitplayers < 2)
    {
	if (menuactive || menuactivestate || !viewactivestate)
	    borderdrawcount = 3;
	if (borderdrawcount)
	{
	    R_DrawViewBorder ();    // erase old menu stuff
	    borderdrawcount--;
	}

    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;
    
    // draw pause pic
    if (paused)
    {
	if (automapactive)
	    y = 4;
	else if (splitplayers > 1)
	    y = 4;
	else
	    y = viewwindowy+4;
	V_DrawPatchDirect((splitplayers > 1) ? ((SCREENWIDTH-68)/2) : (viewwindowx+(scaledviewwidth-68)/2),
			  y,0,W_CacheLumpName ("M_PAUSE", PU_CACHE));
    }


    // menus go directly to the screen
    M_Drawer ();          // menu is drawn even on top of everything
    NetUpdate ();         // send out any new accumulation


    // normal update
    if (!wipe)
    {
	I_FinishUpdate ();              // page flip or blit buffer
	return;
    }
    
    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

    wipestart = I_GetTime () - 1;

    do
    {
	do
	{
	    nowtime = I_GetTime ();
	    tics = nowtime - wipestart;
	} while (!tics);
	wipestart = nowtime;
	done = wipe_ScreenWipe(wipe_Melt
			       , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
	I_UpdateNoBlit ();
	M_Drawer ();                            // menu is drawn even on top of wipes
	I_FinishUpdate ();                      // page flip or blit buffer
    } while (!done);
}



//
//  D_DoomLoop
//
extern  boolean         demorecording;

void D_DoomLoop (void)
{
#ifdef N64
	n64_local_input_t local_input;
	int local_player;
#endif

    if (demorecording)
	G_BeginRecording ();
		
    if (M_CheckParm ("-debugfile"))
    {
	char    filename[20];
	sprintf (filename,"debug%i.txt",consoleplayer);
	printf ("debug output to: %s\n",filename);
	debugfile = fopen (filename,"w");
    }
	
    I_InitGraphics ();

    while (1)
    {
	// frame syncronous IO operations
	I_StartFrame ();                
	
	// process one or more tics
	if (singletics)
	{
	    I_StartTic ();
	    D_ProcessEvents ();
#ifdef N64
	    if (D_LocalMultiplayerEnabled())
	    {
		for (local_player = 0; local_player < MAXPLAYERS; local_player++)
		{
		    if (!playeringame[local_player])
			continue;

		    I_N64GetLocalInputState(local_player, &local_input);
		    G_BuildTiccmdN64Local(&netcmds[local_player][maketic%BACKUPTICS],
					 local_player,
					 &local_input);
		}
	    }
	    else
#endif
	    {
		G_BuildTiccmd (&netcmds[consoleplayer][maketic%BACKUPTICS]);
	    }
	    if (advancedemo)
		D_DoAdvanceDemo ();
	    M_Ticker ();
	    G_Ticker ();
	    gametic++;
	    maketic++;
	}
	else
	{
	    TryRunTics (); // will run at least one tic
	}
		
	S_UpdateSounds (players[consoleplayer].mo);// move positional sounds

	// Update display, next frame, with current state.
	D_Display ();

#ifndef SNDSERV
	// Sound mixing for the buffer is snychronous.
	I_UpdateSound();
#endif	
	// Synchronous sound output is explicitly called.
#ifndef SNDINTR
	// Update sound output.
	I_SubmitSound();
#endif
    }
}



//
//  DEMO LOOP
//
int             demosequence;
int             pagetic;
char                    *pagename;


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    if (--pagetic < 0)
	D_AdvanceDemo ();
}



//
// D_PageDrawer
//
void D_PageDrawer (void)
{
    V_DrawPatch (0,0, 0, W_CacheLumpName(pagename, PU_CACHE));
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
 void D_DoAdvanceDemo (void)
{
    players[consoleplayer].playerstate = PST_LIVE;  // not reborn
    advancedemo = false;
    usergame = false;               // no save / end game here
    paused = false;
    gameaction = ga_nothing;

    if ( gamemode == retail )
      demosequence = (demosequence+1)%7;
    else
      demosequence = (demosequence+1)%6;
    
    switch (demosequence)
    {
      case 0:
	if ( gamemode == commercial )
	    pagetic = 35 * 11;
	else
	    pagetic = 170;
	gamestate = GS_DEMOSCREEN;
	pagename = "TITLEPIC";
	if ( gamemode == commercial )
	  S_StartMusic(mus_dm2ttl);
	else
	  S_StartMusic (mus_intro);
	break;
      case 1:
	G_DeferedPlayDemo ("demo1");
	break;
      case 2:
	pagetic = 200;
	gamestate = GS_DEMOSCREEN;
	pagename = "CREDIT";
	break;
      case 3:
	G_DeferedPlayDemo ("demo2");
	break;
      case 4:
	gamestate = GS_DEMOSCREEN;
	if ( gamemode == commercial)
	{
	    pagetic = 35 * 11;
	    pagename = "TITLEPIC";
	    S_StartMusic(mus_dm2ttl);
	}
	else
	{
	    pagetic = 200;

	    if ( gamemode == retail )
	      pagename = "CREDIT";
	    else if (W_CheckNumForName("HELP2") != -1)
	      pagename = "HELP2";
	    else if (W_CheckNumForName("HELP1") != -1)
	      pagename = "HELP1";
	    else
	      pagename = "CREDIT";
	}
	break;
      case 5:
	G_DeferedPlayDemo ("demo3");
	break;
        // THE DEFINITIVE DOOM Special Edition demo
      case 6:
	G_DeferedPlayDemo ("demo4");
	break;
    }
}



//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}




//      print title for every printed line
char            title[128];



//
// D_AddFile
//
void D_AddFile (char *file)
{
    int     numwadfiles;
    char    *newfile;
	
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
	;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);
	
    wadfiles[numwadfiles] = newfile;

#ifdef N64
	N64_DEBUGF("D_AddFile[%d]: %s\n", numwadfiles, newfile);
#endif
}

#ifdef N64
static void D_N64ResetWadFileList(void)
{
	int i;

	for (i = 0; i < MAXWADFILES; i++)
	{
		if (wadfiles[i])
		{
			free(wadfiles[i]);
			wadfiles[i] = NULL;
		}
	}
}

static char d_n64_save_key[17] = "DOOM";

static int D_N64StrCaseCmp(const char* left, const char* right)
{
	unsigned char lc;
	unsigned char rc;

	if (!left || !right)
		return (left == right) ? 0 : (left ? 1 : -1);

	for (;;)
	{
		lc = (unsigned char)(*left++);
		rc = (unsigned char)(*right++);

		if (lc >= 'A' && lc <= 'Z')
			lc = (unsigned char)(lc + ('a' - 'A'));
		if (rc >= 'A' && rc <= 'Z')
			rc = (unsigned char)(rc + ('a' - 'A'));

		if (lc != rc || !lc || !rc)
			return (int)lc - (int)rc;
	}
}

static const char* D_N64BaseName(const char* path)
{
	const char* base;

	base = path;
	if (!path)
		return "";

	while (*path)
	{
		if (*path == '/' || *path == '\\')
			base = path + 1;
		path++;
	}

	return base;
}

static void D_N64BuildSaveKey(const char* path)
{
	const char* name;
	size_t i;
	size_t out;
	unsigned char ch;

	name = D_N64BaseName(path);
	memset(d_n64_save_key, 0, sizeof(d_n64_save_key));

	out = 0;
	for (i = 0; name[i] && name[i] != '.' && out < sizeof(d_n64_save_key) - 1; i++)
	{
		ch = (unsigned char)name[i];
		if (ch >= 'a' && ch <= 'z')
			ch = (unsigned char)(ch - ('a' - 'A'));

		if ((ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9'))
			d_n64_save_key[out++] = (char)ch;
	}

	if (!out)
		strcpy(d_n64_save_key, "DOOM");
}

const char* D_N64GetSaveKey(void)
{
	return d_n64_save_key;
}

static GameMode_t D_N64GamemodeFromWad(const char* path)
{
	const char* name;

	name = D_N64BaseName(path);

	if (!D_N64StrCaseCmp(name, "doom1.wad"))
		return shareware;

	if (!D_N64StrCaseCmp(name, "doomu.wad"))
		return retail;

	if (!D_N64StrCaseCmp(name, "doom2.wad")
		|| !D_N64StrCaseCmp(name, "doom2f.wad")
		|| !D_N64StrCaseCmp(name, "plutonia.wad")
		|| !D_N64StrCaseCmp(name, "tnt.wad"))
	{
		return commercial;
	}

	if (!D_N64StrCaseCmp(name, "doom.wad"))
		return registered;

	return registered;
}

static int D_N64ValidateIwad(const char* path)
{
	int fd;
	int bytes_read;
	unsigned char sig[4];

	if (!path || !path[0])
		return 0;

	fd = open(path, O_RDONLY | O_BINARY);
	if (fd < 0)
	{
		N64_DEBUGF("IdentifyVersion: open failed for %s\n", path);
		return 0;
	}

	bytes_read = (int)read(fd, sig, sizeof(sig));
	close(fd);

	if (bytes_read != (int)sizeof(sig))
	{
		N64_DEBUGF("IdentifyVersion: short read on %s\n", path);
		return 0;
	}

	if (sig[0] == 'I' && sig[1] == 'W' && sig[2] == 'A' && sig[3] == 'D')
		return 1;

	N64_DEBUGF("IdentifyVersion: %s header=%c%c%c%c (expected IWAD)\n",
		path,
		sig[0],
		sig[1],
		sig[2],
		sig[3]);
	return 0;
}
#endif

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion (void)
{

#ifdef N64
	const char* selected_wad;
	const char* base_iwad;
	int selected_is_iwad;

	selected_wad = I_N64GetSelectedWadPath();
	if (!selected_wad || !selected_wad[0])
	    selected_wad = "rom:/doom.wad";
	base_iwad = I_N64GetSelectedBaseIwadPath();
	if (!base_iwad || !base_iwad[0])
	    base_iwad = selected_wad;

	N64_DEBUGF("IdentifyVersion: selected_wad=%s base_iwad=%s\n",
	          selected_wad,
	          base_iwad);

	selected_is_iwad = D_N64ValidateIwad(selected_wad);
	if (selected_is_iwad)
	    base_iwad = selected_wad;

	if (!D_N64ValidateIwad(base_iwad))
	{
	    char reject_message[96];

	    snprintf(reject_message,
	             sizeof(reject_message),
	             "LAUNCH BLOCKED: %s FAILED IWAD CHECK",
	             D_N64BaseName(base_iwad));
	    I_N64SetBrowserStatusMessage(reject_message);
	    N64_DEBUGF("IdentifyVersion: incompatible base_iwad=%s, returning to browser\n",
	              base_iwad);
	    I_N64ReturnToBrowser();
	    return;
	}

	gamemode = D_N64GamemodeFromWad(base_iwad);
	D_N64BuildSaveKey(selected_is_iwad ? base_iwad : selected_wad);
	N64_DEBUGF("IdentifyVersion: gamemode=%d\n", (int)gamemode);
	N64_DEBUGF("IdentifyVersion: save_key=%s\n", d_n64_save_key);
	D_AddFile ((char*)base_iwad);

	if (!selected_is_iwad)
	{
	    modifiedgame = true;
	    D_AddFile ((char*)selected_wad);
	    N64_DEBUGF("IdentifyVersion: loading PWAD %s on base IWAD %s\n",
	              selected_wad,
	              base_iwad);
	}

	strcpy (basedefault, "doom.cfg");
	return;
#else

    char*	doom1wad;
    char*	doomwad;
    char*	doomuwad;
    char*	doom2wad;

    char*	doom2fwad;
    char*	plutoniawad;
    char*	tntwad;

#ifdef NORMALUNIX
    char *home;
    char *doomwaddir;
    doomwaddir = getenv("DOOMWADDIR");
    if (!doomwaddir)
	doomwaddir = ".";

    // Commercial.
    doom2wad = malloc(strlen(doomwaddir)+1+9+1);
    sprintf(doom2wad, "%s/doom2.wad", doomwaddir);

    // Retail.
    doomuwad = malloc(strlen(doomwaddir)+1+8+1);
    sprintf(doomuwad, "%s/doomu.wad", doomwaddir);
    
    // Registered.
    doomwad = malloc(strlen(doomwaddir)+1+8+1);
    sprintf(doomwad, "%s/doom.wad", doomwaddir);
    
    // Shareware.
    doom1wad = malloc(strlen(doomwaddir)+1+9+1);
    sprintf(doom1wad, "%s/doom1.wad", doomwaddir);

     // Bug, dear Shawn.
    // Insufficient malloc, caused spurious realloc errors.
    plutoniawad = malloc(strlen(doomwaddir)+1+/*9*/12+1);
    sprintf(plutoniawad, "%s/plutonia.wad", doomwaddir);

    tntwad = malloc(strlen(doomwaddir)+1+9+1);
    sprintf(tntwad, "%s/tnt.wad", doomwaddir);


    // French stuff.
    doom2fwad = malloc(strlen(doomwaddir)+1+10+1);
    sprintf(doom2fwad, "%s/doom2f.wad", doomwaddir);

    home = getenv("HOME");
    if (!home)
      I_Error("Please set $HOME to your home directory");
    sprintf(basedefault, "%s/.doomrc", home);
#endif

    if (M_CheckParm ("-shdev"))
    {
	gamemode = shareware;
	devparm = true;
	D_AddFile (DEVDATA"doom1.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if (M_CheckParm ("-regdev"))
    {
	gamemode = registered;
	devparm = true;
	D_AddFile (DEVDATA"doom.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/texture2.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if (M_CheckParm ("-comdev"))
    {
	gamemode = commercial;
	devparm = true;
	/* I don't bother
	if(plutonia)
	    D_AddFile (DEVDATA"plutonia.wad");
	else if(tnt)
	    D_AddFile (DEVDATA"tnt.wad");
	else*/
	    D_AddFile (DEVDATA"doom2.wad");
	    
	D_AddFile (DEVMAPS"cdata/texture1.lmp");
	D_AddFile (DEVMAPS"cdata/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    if ( !access (doom2fwad,R_OK) )
    {
	gamemode = commercial;
	// C'est ridicule!
	// Let's handle languages in config files, okay?
	language = french;
	printf("French version\n");
	D_AddFile (doom2fwad);
	return;
    }

    if ( !access (doom2wad,R_OK) )
    {
	gamemode = commercial;
	D_AddFile (doom2wad);
	return;
    }

    if ( !access (plutoniawad, R_OK ) )
    {
      gamemode = commercial;
      D_AddFile (plutoniawad);
      return;
    }

    if ( !access ( tntwad, R_OK ) )
    {
      gamemode = commercial;
      D_AddFile (tntwad);
      return;
    }

    if ( !access (doomuwad,R_OK) )
    {
      gamemode = retail;
      D_AddFile (doomuwad);
      return;
    }

    if ( !access (doomwad,R_OK) )
    {
      gamemode = registered;
      D_AddFile (doomwad);
      return;
    }

    if ( !access (doom1wad,R_OK) )
    {
      gamemode = shareware;
      D_AddFile (doom1wad);
      return;
    }

    printf("Game mode indeterminate.\n");
    gamemode = indetermined;

    // We don't abort. Let's see what the PWAD contains.
    //exit(1);
    //I_Error ("Game mode indeterminate\n");
#endif
}

//
// Find a Response File
//
void FindResponseFile (void)
{
    int             i;
#define MAXARGVS        100
	
    for (i = 1;i < myargc;i++)
	if (myargv[i][0] == '@')
	{
	    FILE *          handle;
	    int             size;
	    int             k;
	    int             index;
	    int             indexinfile;
	    char    *infile;
	    char    *file;
	    char    *moreargs[20];
	    char    *firstargv;
			
	    // READ THE RESPONSE FILE INTO MEMORY
	    handle = fopen (&myargv[i][1],"rb");
	    if (!handle)
	    {
		printf ("\nNo such response file!");
		exit(1);
	    }
	    printf("Found response file %s!\n",&myargv[i][1]);
	    fseek (handle,0,SEEK_END);
	    size = ftell(handle);
	    fseek (handle,0,SEEK_SET);
	    file = malloc (size);
	    fread (file,size,1,handle);
	    fclose (handle);
			
	    // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
	    for (index = 0,k = i+1; k < myargc; k++)
		moreargs[index++] = myargv[k];
			
	    firstargv = myargv[0];
	    myargv = malloc(sizeof(char *)*MAXARGVS);
	    memset(myargv,0,sizeof(char *)*MAXARGVS);
	    myargv[0] = firstargv;
			
	    infile = file;
	    indexinfile = k = 0;
	    indexinfile++;  // SKIP PAST ARGV[0] (KEEP IT)
	    do
	    {
		myargv[indexinfile++] = infile+k;
		while(k < size &&
		      ((*(infile+k)>= ' '+1) && (*(infile+k)<='z')))
		    k++;
		*(infile+k) = 0;
		while(k < size &&
		      ((*(infile+k)<= ' ') || (*(infile+k)>'z')))
		    k++;
	    } while(k < size);
			
	    for (k = 0;k < index;k++)
		myargv[indexinfile++] = moreargs[k];
	    myargc = indexinfile;
	
	    // DISPLAY ARGS
	    printf("%d command-line args:\n",myargc);
	    for (k=1;k<myargc;k++)
		printf("%s\n",myargv[k]);

	    break;
	}
}


//
// D_DetectEpisodes
// Counts DOOM 1 style episodes (ExMy) present in the loaded WAD set by
// probing for each episode's first map marker (E<n>M1). Used to support
// extra episodes added by PWADs (e.g. SIGIL adds episode 5) on top of the
// stock retail four. No effect for commercial (MAPxx) WADs.
//
void D_DetectEpisodes (void)
{
    char	marker[9];
    int		ep;

    d_episodes = 0;

    // Commercial uses MAPxx, not ExMy episodes.
    if (gamemode == commercial)
	return;

    for (ep = 1; ep <= 9; ep++)
    {
	marker[0] = 'E';
	marker[1] = (char)('0' + ep);
	marker[2] = 'M';
	marker[3] = '1';
	marker[4] = 0;

	if (W_CheckNumForName(marker) < 0)
	    break;		// episodes must be contiguous from 1

	d_episodes = ep;
    }

    N64_DEBUGF("D_DetectEpisodes: gamemode=%d episodes=%d\n",
	      (int)gamemode, d_episodes);

    // Game mode is guessed from the IWAD filename, which cannot tell the
    // 3-episode registered DOOM from the 4-episode Ultimate DOOM (both are
    // named doom.wad). Trust the actual episode count instead: a 4th episode
    // (E4M1) means retail/Ultimate, and PWADs adding more (SIGIL = E5) also
    // need retail behaviour (no registered/shareware episode gating).
    if (d_episodes >= 4 && gamemode != retail && gamemode != commercial)
    {
	N64_DEBUGF("D_DetectEpisodes: promoting gamemode %d -> retail for %d episodes\n",
		  (int)gamemode, d_episodes);
	gamemode = retail;
    }
}


//
// D_DoomMain
//
void D_DoomMain (void)
{
    int             p;
    char                    file[256];

    FindResponseFile ();

#ifdef N64
	D_N64ResetWadFileList();
#endif
	
    IdentifyVersion ();
	
    setbuf (stdout, NULL);
    modifiedgame = false;

#ifdef N64
    {
	int n64_wadfile_count;

	n64_wadfile_count = 0;
	while (n64_wadfile_count < MAXWADFILES && wadfiles[n64_wadfile_count])
	    n64_wadfile_count++;

	if (n64_wadfile_count > 1)
	    modifiedgame = true;
    }
#endif
	
    nomonsters = M_CheckParm ("-nomonsters");
    respawnparm = M_CheckParm ("-respawn");
    fastparm = M_CheckParm ("-fast");
    devparm = M_CheckParm ("-devparm");
    if (M_CheckParm ("-altdeath"))
	deathmatch = 2;
    else if (M_CheckParm ("-deathmatch"))
	deathmatch = 1;

    switch ( gamemode )
    {
      case retail:
	sprintf (title,
		 "                         "
		 "The Ultimate DOOM Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case shareware:
	sprintf (title,
		 "                            "
		 "DOOM Shareware Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case registered:
	sprintf (title,
		 "                            "
		 "DOOM Registered Startup v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case commercial:
	sprintf (title,
		 "                         "
		 "DOOM 2: Hell on Earth v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
/*FIXME
       case pack_plut:
	sprintf (title,
		 "                   "
		 "DOOM 2: Plutonia Experiment v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
      case pack_tnt:
	sprintf (title,
		 "                     "
		 "DOOM 2: TNT - Evilution v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
*/
      default:
	sprintf (title,
		 "                     "
		 "Public DOOM - v%i.%i"
		 "                           ",
		 VERSION/100,VERSION%100);
	break;
    }
    
    printf ("%s\n",title);

    if (devparm)
	printf(D_DEVSTR);
    
    if (M_CheckParm("-cdrom"))
    {
	printf(D_CDROM);
	mkdir("c:\\doomdata",0);
	strcpy (basedefault,"c:/doomdata/default.cfg");
    }	
    
    // turbo option
    if ( (p=M_CheckParm ("-turbo")) )
    {
	int     scale = 200;
	extern int forwardmove[2];
	extern int sidemove[2];
	
	if (p<myargc-1)
	    scale = atoi (myargv[p+1]);
	if (scale < 10)
	    scale = 10;
	if (scale > 400)
	    scale = 400;
	printf ("turbo scale: %i%%\n",scale);
	forwardmove[0] = forwardmove[0]*scale/100;
	forwardmove[1] = forwardmove[1]*scale/100;
	sidemove[0] = sidemove[0]*scale/100;
	sidemove[1] = sidemove[1]*scale/100;
    }
    
    // add any files specified on the command line with -file wadfile
    // to the wad list
    //
    // convenience hack to allow -wart e m to add a wad file
    // prepend a tilde to the filename so wadfile will be reloadable
    p = M_CheckParm ("-wart");
    if (p)
    {
	myargv[p][4] = 'p';     // big hack, change to -warp

	// Map name handling.
	switch (gamemode )
	{
	  case shareware:
	  case retail:
	  case registered:
	    sprintf (file,"~"DEVMAPS"E%cM%c.wad",
		     myargv[p+1][0], myargv[p+2][0]);
	    printf("Warping to Episode %s, Map %s.\n",
		   myargv[p+1],myargv[p+2]);
	    break;
	    
	  case commercial:
	  default:
	    p = atoi (myargv[p+1]);
	    if (p<10)
	      sprintf (file,"~"DEVMAPS"cdata/map0%i.wad", p);
	    else
	      sprintf (file,"~"DEVMAPS"cdata/map%i.wad", p);
	    break;
	}
	D_AddFile (file);
    }
	
    p = M_CheckParm ("-file");
    if (p)
    {
	// the parms after p are wadfile/lump names,
	// until end of parms or another - preceded parm
	modifiedgame = true;            // homebrew levels
	while (++p != myargc && myargv[p][0] != '-')
	    D_AddFile (myargv[p]);
    }

    p = M_CheckParm ("-playdemo");

    if (!p)
	p = M_CheckParm ("-timedemo");

    if (p && p < myargc-1)
    {
	sprintf (file,"%s.lmp", myargv[p+1]);
	D_AddFile (file);
	printf("Playing demo %s.lmp.\n",myargv[p+1]);
    }
    
    // get skill / episode / map from parms
    startskill = sk_medium;
    startepisode = 1;
    startmap = 1;
    autostart = false;

		
    p = M_CheckParm ("-skill");
    if (p && p < myargc-1)
    {
	startskill = myargv[p+1][0]-'1';
	autostart = true;
    }

    p = M_CheckParm ("-episode");
    if (p && p < myargc-1)
    {
	startepisode = myargv[p+1][0]-'0';
	startmap = 1;
	autostart = true;
    }
	
    p = M_CheckParm ("-timer");
    if (p && p < myargc-1 && deathmatch)
    {
	int     time;
	time = atoi(myargv[p+1]);
	printf("Levels will end after %d minute",time);
	if (time>1)
	    printf("s");
	printf(".\n");
    }

    p = M_CheckParm ("-avg");
    if (p && p < myargc-1 && deathmatch)
	printf("Austin Virtual Gaming: Levels will end after 20 minutes\n");

    p = M_CheckParm ("-warp");
    if (p && p < myargc-1)
    {
	if (gamemode == commercial)
	    startmap = atoi (myargv[p+1]);
	else
	{
	    startepisode = myargv[p+1][0]-'0';
	    startmap = myargv[p+2][0]-'0';
	}
	autostart = true;
    }
    
    // init subsystems
    printf ("V_Init: allocate screens.\n");
    V_Init ();

    printf ("M_LoadDefaults: Load system defaults.\n");
    M_LoadDefaults ();              // load before initing other systems

    printf ("Z_Init: Init zone memory allocation daemon. \n");
    Z_Init ();

    printf ("W_Init: Init WADfiles.\n");

#ifdef N64
	{
	int wad_index;
	for (wad_index = 0; wadfiles[wad_index]; wad_index++)
	    N64_DEBUGF("W_InitMultipleFiles input[%d]=%s\n", wad_index, wadfiles[wad_index]);
	I_N64LogMemoryStats("d_main:before_W_InitMultipleFiles");
	}
#endif

    W_InitMultipleFiles (wadfiles);

#ifdef N64
    I_N64LogMemoryStats("d_main:after_W_InitMultipleFiles");
#endif

    // Detect DOOM 1 style episodes (incl. PWAD-added ones like SIGIL's E5)
    // now that all lumps are available.
    D_DetectEpisodes ();
    

    // Check for -file in shareware
    if (modifiedgame)
    {
	// These are the lumps that will be checked in IWAD,
	// if any one is not present, execution will be aborted.
	char name[23][8]=
	{
	    "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
	    "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
	    "dphoof","bfgga0","heada1","cybra1","spida1d1"
	};
	int i;
	
	if ( gamemode == shareware)
	    I_Error("\nYou cannot -file with the shareware "
		    "version. Register!");

	// Check for fake IWAD with right name,
	// but w/o all the lumps of the registered version. 
	if (gamemode == registered)
	    for (i = 0;i < 23; i++)
		if (W_CheckNumForName(name[i])<0)
		    I_Error("\nThis is not the registered version.");
    }
    
    // Iff additonal PWAD files are used, print modified banner
    if (modifiedgame)
    {
	/*m*/printf (
	    "===========================================================================\n"
	    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
	    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
	    "        You will not receive technical support for modified games.\n"
	    "                      press enter to continue\n"
	    "===========================================================================\n"
	    );
	getchar ();
    }
	

    // Check and print which version is executed.
    switch ( gamemode )
    {
      case shareware:
      case indetermined:
	printf (
	    "===========================================================================\n"
	    "                                Shareware!\n"
	    "===========================================================================\n"
	);
	break;
      case registered:
      case retail:
      case commercial:
	printf (
	    "===========================================================================\n"
	    "                 Commercial product - do not distribute!\n"
	    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
	    "===========================================================================\n"
	);
	break;
	
      default:
	// Ouch.
	break;
    }

    printf ("M_Init: Init miscellaneous info.\n");
    M_Init ();

    printf ("R_Init: Init DOOM refresh daemon - ");
    R_Init ();

    printf ("\nP_Init: Init Playloop state.\n");
    P_Init ();

    printf ("I_Init: Setting up machine state.\n");
    I_Init ();

    printf ("D_CheckNetGame: Checking network game status.\n");
    D_CheckNetGame ();

    printf ("S_Init: Setting up sound.\n");
    S_Init (snd_SfxVolume /* *8 */, snd_MusicVolume /* *8*/ );

    printf ("HU_Init: Setting up heads up display.\n");
    HU_Init ();

    printf ("ST_Init: Init status bar.\n");
    ST_Init ();

    // check for a driver that wants intermission stats
    p = M_CheckParm ("-statcopy");
    if (p && p<myargc-1)
    {
	// for statistics driver
	extern  void*	statcopy;                            

	statcopy = (void*)atoi(myargv[p+1]);
	printf ("External statistics registered.\n");
    }
    
    // start the apropriate game based on parms
    p = M_CheckParm ("-record");

    if (p && p < myargc-1)
    {
	G_RecordDemo (myargv[p+1]);
	autostart = true;
    }
	
    p = M_CheckParm ("-playdemo");
    if (p && p < myargc-1)
    {
	singledemo = true;              // quit after one demo
	G_DeferedPlayDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-timedemo");
    if (p && p < myargc-1)
    {
	G_TimeDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-loadgame");
    if (p && p < myargc-1)
    {
	if (M_CheckParm("-cdrom"))
	    sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
	else
	    sprintf(file, SAVEGAMENAME"%c.dsg",myargv[p+1][0]);
	G_LoadGame (file);
    }
	

    if ( gameaction != ga_loadgame )
    {
	if (autostart || netgame)
	    G_InitNew (startskill, startepisode, startmap);
	else
	    D_StartTitle ();                // start up intro loop

    }

    D_DoomLoop ();  // never returns
}
